name: aqwatrak
description: Water tracker app (AqwaTrak)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # API
  http: ^1.2.2

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3

  # Local storage + profile
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
